apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service-prod
spec:
  type: NodePort
  selector:
    app: heart-disease
    env: prod
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007