name: Pytest Debug

on:
  workflow_dispatch:
  push:
    paths:
      - "M-Tech. Semester 3/MLOPS/Assignment-1/heart-disease-mlops/**"
      - ".github/workflows/pytest-debug.yml"

defaults:
  run:
    working-directory: "M-Tech. Semester 3/MLOPS/Assignment-1/heart-disease-mlops"

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Show test files
        run: |
          pwd
          ls
          ls tests

      - name: Collect tests
        run: pytest --collect-only -q

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -v
